
package com.oneconnect.payments.paygate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PayHOSTService", targetNamespace = "http://www.paygate.co.za/PayHOST", wsdlLocation = "https://secure.paygate.co.za/payhost/process.trans?wsdl")
public class PayHOSTService
    extends Service
{

    private final static URL PAYHOSTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYHOSTSERVICE_EXCEPTION;
    private final static QName PAYHOSTSERVICE_QNAME = new QName("http://www.paygate.co.za/PayHOST", "PayHOSTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://secure.paygate.co.za/payhost/process.trans?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYHOSTSERVICE_WSDL_LOCATION = url;
        PAYHOSTSERVICE_EXCEPTION = e;
    }

    public PayHOSTService() {
        super(__getWsdlLocation(), PAYHOSTSERVICE_QNAME);
    }

    public PayHOSTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYHOSTSERVICE_QNAME, features);
    }

    public PayHOSTService(URL wsdlLocation) {
        super(wsdlLocation, PAYHOSTSERVICE_QNAME);
    }

    public PayHOSTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYHOSTSERVICE_QNAME, features);
    }

    public PayHOSTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PayHOSTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PayHOST
     */
    @WebEndpoint(name = "PayHOSTSoap11")
    public PayHOST getPayHOSTSoap11() {
        return super.getPort(new QName("http://www.paygate.co.za/PayHOST", "PayHOSTSoap11"), PayHOST.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PayHOST
     */
    @WebEndpoint(name = "PayHOSTSoap11")
    public PayHOST getPayHOSTSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.paygate.co.za/PayHOST", "PayHOSTSoap11"), PayHOST.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYHOSTSERVICE_EXCEPTION!= null) {
            throw PAYHOSTSERVICE_EXCEPTION;
        }
        return PAYHOSTSERVICE_WSDL_LOCATION;
    }

}
