
package com.oneconnect.payments.payu;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnterpriseAPISoap", targetNamespace = "http://soap.api.controller.web.payjar.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnterpriseAPISoap {


    /**
     * 
     * @param soulstace
     * @param basket
     * @param transactionRecord
     * @param bankTransfer
     * @param customfield
     * @param sbux
     * @param safekey
     * @param debitcard
     * @param thirdParty
     * @param api
     * @param credit
     * @param bankAccount
     * @param additionalInformation
     * @param wallet
     * @param autopay
     * @param rcs
     * @param ebucks
     * @param loyalty
     * @param discoveryMiles
     * @param eWallet
     * @param creditcard
     * @param transactionType
     * @param eft
     * @param fraud
     * @param globalpay
     * @param authenticationType
     * @param payPal
     * @param customer
     * @return
     *     returns com.oneconnect.payments.payu.DoTransactionResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doTransaction", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.DoTransaction")
    @ResponseWrapper(localName = "doTransactionResponse", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.DoTransactionResponse")
    public DoTransactionResponseMessage doTransaction(
            @WebParam(name = "Api", targetNamespace = "")
                    String api,
            @WebParam(name = "Safekey", targetNamespace = "")
                    String safekey,
            @WebParam(name = "TransactionType", targetNamespace = "")
                    TransactionType transactionType,
            @WebParam(name = "AuthenticationType", targetNamespace = "")
                    AuthenticationType authenticationType,
            @WebParam(name = "AdditionalInformation", targetNamespace = "")
                    AdditionalInfo additionalInformation,
            @WebParam(name = "Customer", targetNamespace = "")
                    Customer customer,
            @WebParam(name = "Basket", targetNamespace = "")
                    Basket basket,
            @WebParam(name = "Fraud", targetNamespace = "")
                    Fraud fraud,
            @WebParam(name = "Creditcard", targetNamespace = "")
                    List<CreditCard> creditcard,
            @WebParam(name = "Eft", targetNamespace = "")
                    List<Eft> eft,
            @WebParam(name = "DiscoveryMiles", targetNamespace = "")
                    List<DiscoveryMiles> discoveryMiles,
            @WebParam(name = "PayPal", targetNamespace = "")
                    List<PayPal> payPal,
            @WebParam(name = "Debitcard", targetNamespace = "")
                    List<DebitCard> debitcard,
            @WebParam(name = "Loyalty", targetNamespace = "")
                    List<LoyaltyCard> loyalty,
            @WebParam(name = "BankTransfer", targetNamespace = "")
                    List<BankTransfer> bankTransfer,
            @WebParam(name = "Wallet", targetNamespace = "")
                    List<Wallet> wallet,
            @WebParam(name = "ThirdParty", targetNamespace = "")
                    List<ThirdParty> thirdParty,
            @WebParam(name = "Ebucks", targetNamespace = "")
                    List<Ebucks> ebucks,
            @WebParam(name = "Autopay", targetNamespace = "")
                    AutoPay autopay,
            @WebParam(name = "Soulstace", targetNamespace = "")
                    Soulstace soulstace,
            @WebParam(name = "Globalpay", targetNamespace = "")
                    Globalpay globalpay,
            @WebParam(name = "Customfield", targetNamespace = "")
                    List<CustomField> customfield,
            @WebParam(name = "Credit", targetNamespace = "")
                    Credit credit,
            @WebParam(name = "TransactionRecord", targetNamespace = "")
                    TransactionRecord transactionRecord,
            @WebParam(name = "Sbux", targetNamespace = "")
                    List<Sbux> sbux,
            @WebParam(name = "RCS", targetNamespace = "")
                    Rcs rcs,
            @WebParam(name = "BankAccount", targetNamespace = "")
                    BankAccount bankAccount,
            @WebParam(name = "EWallet", targetNamespace = "")
                    EWallet eWallet);

    /**
     * 
     * @param additionalInformation
     * @param customfield
     * @param api
     * @param safekey
     * @param managePaymentMethodType
     * @param customer
     * @return
     *     returns com.oneconnect.payments.payu.ManagePaymentMethodResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "managePaymentMethod", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.ManagePaymentMethod")
    @ResponseWrapper(localName = "managePaymentMethodResponse", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.ManagePaymentMethodResponse")
    public ManagePaymentMethodResponseMessage managePaymentMethod(
            @WebParam(name = "Api", targetNamespace = "")
                    String api,
            @WebParam(name = "Safekey", targetNamespace = "")
                    String safekey,
            @WebParam(name = "managePaymentMethodType", targetNamespace = "")
                    ManagePaymentMethodType managePaymentMethodType,
            @WebParam(name = "AdditionalInformation", targetNamespace = "")
                    AdditionalInfo additionalInformation,
            @WebParam(name = "Customer", targetNamespace = "")
                    Customer customer,
            @WebParam(name = "Customfield", targetNamespace = "")
                    List<CustomField> customfield);

    /**
     * 
     * @param customfield
     * @param deleteTransactionType
     * @param api
     * @param safekey
     * @return
     *     returns com.oneconnect.payments.payu.DeleteTransactionResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doDeleteTransaction", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.DoDeleteTransaction")
    @ResponseWrapper(localName = "doDeleteTransactionResponse", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.DoDeleteTransactionResponse")
    public DeleteTransactionResponseMessage doDeleteTransaction(
            @WebParam(name = "Api", targetNamespace = "")
                    String api,
            @WebParam(name = "Safekey", targetNamespace = "")
                    String safekey,
            @WebParam(name = "deleteTransactionType", targetNamespace = "")
                    DeleteTransactionType deleteTransactionType,
            @WebParam(name = "Customfield", targetNamespace = "")
                    List<CustomField> customfield);

    /**
     * 
     * @param additionalInformation
     * @param api
     * @param safekey
     * @return
     *     returns com.oneconnect.payments.payu.GetTransactionResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransaction", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.GetTransaction")
    @ResponseWrapper(localName = "getTransactionResponse", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.GetTransactionResponse")
    public GetTransactionResponseMessage getTransaction(
            @WebParam(name = "Api", targetNamespace = "")
                    String api,
            @WebParam(name = "Safekey", targetNamespace = "")
                    String safekey,
            @WebParam(name = "AdditionalInformation", targetNamespace = "")
                    AdditionalInfo additionalInformation);

    /**
     * 
     * @param customfield
     * @param lookupTransactionType
     * @param api
     * @param safekey
     * @return
     *     returns com.oneconnect.payments.payu.LookupTransactionResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLookupTransaction", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.GetLookupTransaction")
    @ResponseWrapper(localName = "getLookupTransactionResponse", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.GetLookupTransactionResponse")
    public LookupTransactionResponseMessage getLookupTransaction(
            @WebParam(name = "Api", targetNamespace = "")
                    String api,
            @WebParam(name = "Safekey", targetNamespace = "")
                    String safekey,
            @WebParam(name = "lookupTransactionType", targetNamespace = "")
                    LookupTransactionType lookupTransactionType,
            @WebParam(name = "Customfield", targetNamespace = "")
                    List<CustomField> customfield);

    /**
     * 
     * @param soulstace
     * @param additionalInformation
     * @param basket
     * @param transactionRecord
     * @param bankTransfer
     * @param autopay
     * @param customfield
     * @param ebucks
     * @param loyalty
     * @param eWallet
     * @param safekey
     * @param creditcard
     * @param transactionType
     * @param eft
     * @param stage
     * @param fraud
     * @param globalpay
     * @param api
     * @param customer
     * @return
     *     returns com.oneconnect.payments.payu.SetTransactionResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setTransaction", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.SetTransaction")
    @ResponseWrapper(localName = "setTransactionResponse", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.SetTransactionResponse")
    public SetTransactionResponseMessage setTransaction(
            @WebParam(name = "Api", targetNamespace = "")
                    String api,
            @WebParam(name = "Safekey", targetNamespace = "")
                    String safekey,
            @WebParam(name = "TransactionType", targetNamespace = "")
                    TransactionType transactionType,
            @WebParam(name = "Stage", targetNamespace = "")
                    Boolean stage,
            @WebParam(name = "AdditionalInformation", targetNamespace = "")
                    AdditionalInfo additionalInformation,
            @WebParam(name = "Customer", targetNamespace = "")
                    Customer customer,
            @WebParam(name = "Basket", targetNamespace = "")
                    Basket basket,
            @WebParam(name = "Fraud", targetNamespace = "")
                    Fraud fraud,
            @WebParam(name = "Creditcard", targetNamespace = "")
                    List<CreditCard> creditcard,
            @WebParam(name = "Eft", targetNamespace = "")
                    List<Eft> eft,
            @WebParam(name = "Loyalty", targetNamespace = "")
                    List<LoyaltyCard> loyalty,
            @WebParam(name = "BankTransfer", targetNamespace = "")
                    List<BankTransfer> bankTransfer,
            @WebParam(name = "Ebucks", targetNamespace = "")
                    Ebucks ebucks,
            @WebParam(name = "Autopay", targetNamespace = "")
                    AutoPay autopay,
            @WebParam(name = "Soulstace", targetNamespace = "")
                    Soulstace soulstace,
            @WebParam(name = "Globalpay", targetNamespace = "")
                    Globalpay globalpay,
            @WebParam(name = "Customfield", targetNamespace = "")
                    List<CustomField> customfield,
            @WebParam(name = "TransactionRecord", targetNamespace = "")
                    TransactionRecord transactionRecord,
            @WebParam(name = "EWallet", targetNamespace = "")
                    EWallet eWallet);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hi", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.Hi")
    @ResponseWrapper(localName = "hiResponse", targetNamespace = "http://soap.api.controller.web.payjar.com/", className = "com.oneconnect.payments.payu.HiResponse")
    public String hi();

}
