
package com.oneconnectgroup.payuapp.payu;

public enum TransactionType {

    LOOKUP("LOOKUP"),
    MANAGE("MANAGE"),
    MSISDN_LOOKUP("MSISDN_LOOKUP"),
    EFFECT_STAGING("EFFECT_STAGING"),
    RESERVE("RESERVE"),
    RESERVE_CANCEL("RESERVE_CANCEL"),
    PAYMENT("PAYMENT"),
    CROSS_BORDER_PAYMENT("CROSS_BORDER_PAYMENT"),
    BILL_PAYMENT("BILL_PAYMENT"),
    FINALIZE("FINALIZE"),
    BALANCE("BALANCE"),
    MINI_STATEMENT("MINI_STATEMENT"),
    REGISTER("REGISTER"),
    CREDIT("CREDIT"),
    PARTIAL_CREDIT("PARTIAL_CREDIT"),
    TRANSFER("TRANSFER"),
    VERIFY_TRANSACTION("VERIFY_TRANSACTION"),
    REGISTER_LINK("REGISTER_LINK"),
    TOPUP_RESERVE("TOPUP_RESERVE"),
    TOPUP_FINALIZE("TOPUP_FINALIZE"),
    TOPUP_CANCEL("TOPUP_CANCEL"),
    TOPUP("TOPUP"),
    PAYOUT("PAYOUT"),
    COLLECT("COLLECT"),
    ACCOUNT_LOOKUP("ACCOUNT_LOOKUP"),
    RECURRING_PAYMENT("RECURRING_PAYMENT"),
    RECURRING_PAYMENT_SETUP("RECURRING_PAYMENT_SETUP"),
    DEBIT_ORDER("DEBIT_ORDER"),
    DEBIT_ORDER_SETUP("DEBIT_ORDER_SETUP"),
    DEBIT_ORDER_CANCEL("DEBIT_ORDER_CANCEL"),
    SUBSCRIPTION_PAYMENT("SUBSCRIPTION_PAYMENT"),
    SUBSCRIPTION_PAYMENT_SETUP("SUBSCRIPTION_PAYMENT_SETUP"),
    RECURRING_TOKENISE("RECURRING_TOKENISE"),
    REDEEM_UKASH_VOUCHER("REDEEM_UKASH_VOUCHER"),
    ADD_CREDITCARD("ADD_CREDITCARD"),
    EVENT_CARDPURCHASE("EVENT_CARDPURCHASE"),
    VAS_SPEND("VAS_SPEND"),
    VAS_PAY_RECIPIENT_KNOWN("VAS_PAY_RECIPIENT_KNOWN"),
    VAS_PAY_RECIPIENT_UNKNOWN("VAS_PAY_RECIPIENT_UNKNOWN"),
    PROFILE_UPDATE("PROFILE_UPDATE"),
    LOG_JOURNAL_ENTRY("LOG_JOURNAL_ENTRY"),
    LOG_JOURNAL_ENTRY_REVERSE("LOG_JOURNAL_ENTRY_REVERSE"),
    PAYU_DEPOSIT("PAYU_DEPOSIT"),
    PAYU_DEPOSIT_CANCEL("PAYU_DEPOSIT_CANCEL"),
    CHECK_CUST_MAX_BALANCE("CHECK_CUST_MAX_BALANCE"),
    CHECK_CUST_SVA_LIMITS("CHECK_CUST_SVA_LIMITS"),
    VAS_LOOKUP("VAS_LOOKUP"),
    VAS_PROCESS("VAS_PROCESS"),
    VAS_CREDIT("VAS_CREDIT"),
    PENDING_3_DS_COMPLETION("PENDING_3DS_COMPLETION"),
    ONCE_OFF_PAYMENT_AND_DEBIT_ORDER("ONCE_OFF_PAYMENT_AND_DEBIT_ORDER"),
    ONCE_OFF_RESERVE_AND_DEBIT_ORDER("ONCE_OFF_RESERVE_AND_DEBIT_ORDER"),
    P_2_P("P2P"),
    P_2_P_RESERVE("P2P_RESERVE"),
    P_2_P_CANCEL("P2P_CANCEL"),
    P_2_P_FINALIZE("P2P_FINALIZE"),
    VALIDATION("VALIDATION"),
    PROVISION("PROVISION"),
    NOTIFICATION("NOTIFICATION"),
    ADJUSTMENT("ADJUSTMENT"),
    CREDIT_LOOKUP("CREDIT_LOOKUP"),
    WITHDRAWAL("WITHDRAWAL"),
    TRANSFER_CANCEL("TRANSFER_CANCEL"),
    AUTHENTICATION("AUTHENTICATION");
    private final String value;

    TransactionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransactionType fromValue(String v) {
        for (TransactionType c: TransactionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
